# docker-compose.yml

version: "3.9"
services:
  music-app:
    container_name: music-app-api
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    command: npm start
    ports:
      - ${PORT}:${PORT}
